import type { ColumnType } from '@grid-table/view'
import { Table } from '@grid-table/view/src'
import { Tag, Button, Space } from 'antd'
import { useState } from 'react'

const columns: ColumnType[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    width: 100,
    render: (text) => {
      return <a>{text}</a>
    },
  },
  {
    title: 'Age',
    dataIndex: 'age',
    width: 100,
  },
  {
    title: 'Email',
    dataIndex: 'email',
    width: 120,
  },
  {
    title: 'Phone',
    dataIndex: 'phone',
    width: 120,
  },
  {
    title: 'Department',
    dataIndex: 'department',
    width: 100,
  },
  {
    title: 'Position',
    dataIndex: 'position',
    width: 100,
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
    width: 100,
    render: (salary) => `$${salary?.toLocaleString()}`,
  },
  {
    title: 'Start Date',
    dataIndex: 'startDate',
    width: 100,
  },
  {
    title: 'Status',
    dataIndex: 'status',
    width: 80,
    render: (status) => {
      const color = status === 'Active' ? 'green' : status === 'Inactive' ? 'red' : 'orange'
      return <Tag color={color}>{status}</Tag>
    },
  },
  {
    title: 'Address',
    dataIndex: 'address',
    width: 100,
  },
  {
    title: 'Tags',
    dataIndex: 'tags',
    width: 100,
    render: (_, { tags }) => (
      <>
        {(tags as string[]).map((tag) => {
          let color = tag.length > 5 ? 'geekblue' : 'green'
          if (tag === 'loser') {
            color = 'volcano'
          }

          return (
            <Tag color={color} id={tag} key={tag}>
              {tag.toUpperCase()}
            </Tag>
          )
        })}
      </>
    ),
  },
  {
    title: 'Action',
    width: 100,
    fixed: 'right',
    render: (_, record) => {
      return <>操作列</>
    },
  },
]
const data = [
  // 根节点 1-10
  {
    id: '1',
    name: 'Root 1',
    age: 32,
    email: 'root1@company.com',
    phone: '+1-555-0101',
    department: 'Engineering',
    position: 'Tech Lead',
    salary: 120000,
    startDate: '2020-01-15',
    status: 'Active',
    address: 'New York No. 1 Lake Park',
    tags: ['nice', 'developer'],
  },
  {
    id: '2',
    name: 'Root 2',
    age: 42,
    email: 'root2@company.com',
    phone: '+44-555-0102',
    department: 'Marketing',
    position: 'Director',
    salary: 110000,
    startDate: '2018-03-20',
    status: 'Inactive',
    address: 'London No. 1 Lake Park',
    tags: ['loser'],
  },
  {
    id: '3',
    name: 'Root 3',
    age: 32,
    email: 'root3@company.com',
    phone: '+61-555-0103',
    department: 'Education',
    position: 'Manager',
    salary: 95000,
    startDate: '2019-07-10',
    status: 'Active',
    address: 'Sydney No. 1 Lake Park',
    tags: ['cool', 'teacher'],
  },
  {
    id: '4',
    name: 'Root 4',
    age: 35,
    email: 'root4@company.com',
    phone: '+81-555-0104',
    department: 'Management',
    position: 'VP',
    salary: 150000,
    startDate: '2017-11-05',
    status: 'Active',
    address: 'Tokyo No. 1 Lake Park',
    tags: ['manager', 'leader'],
  },
  {
    id: '5',
    name: 'Root 5',
    age: 28,
    email: 'root5@company.com',
    phone: '+33-555-0105',
    department: 'Design',
    position: 'Creative Director',
    salary: 100000,
    startDate: '2021-02-14',
    status: 'Active',
    address: 'Paris No. 1 Lake Park',
    tags: ['designer', 'creative'],
  },
  {
    id: '6',
    name: 'Root 6',
    age: 40,
    email: 'root6@company.com',
    phone: '+49-555-0106',
    department: 'Engineering',
    position: 'Senior Engineer',
    salary: 130000,
    startDate: '2016-09-01',
    status: 'Active',
    address: 'Berlin No. 1 Lake Park',
    tags: ['engineer', 'senior'],
  },
  {
    id: '7',
    name: 'Root 7',
    age: 33,
    email: 'root7@company.com',
    phone: '+7-555-0107',
    department: 'Analytics',
    position: 'Data Scientist',
    salary: 115000,
    startDate: '2019-04-22',
    status: 'Active',
    address: 'Moscow No. 1 Lake Park',
    tags: ['analyst', 'data'],
  },
  {
    id: '8',
    name: 'Root 8',
    age: 37,
    email: 'root8@company.com',
    phone: '+82-555-0108',
    department: 'Product',
    position: 'Product Owner',
    salary: 105000,
    startDate: '2018-12-03',
    status: 'Pending',
    address: 'Seoul No. 1 Lake Park',
    tags: ['product', 'owner'],
  },
  {
    id: '9',
    name: 'Root 9',
    age: 29,
    email: 'root9@company.com',
    phone: '+91-555-0109',
    department: 'QA',
    position: 'QA Manager',
    salary: 85000,
    startDate: '2020-06-18',
    status: 'Active',
    address: 'Mumbai No. 1 Lake Park',
    tags: ['tester', 'qa'],
  },
  {
    id: '10',
    name: 'Root 10',
    age: 31,
    email: 'root10@company.com',
    phone: '+1-555-0110',
    department: 'Architecture',
    position: 'Solutions Architect',
    salary: 140000,
    startDate: '2019-08-12',
    status: 'Active',
    address: 'Toronto No. 1 Lake Park',
    tags: ['architect', 'tech'],
  },

  // Level 1 子节点
  {
    id: '1-1',
    parentId: '1',
    name: 'Child 1-1',
    age: 22,
    email: 'child1-1@company.com',
    phone: '+1-555-0201',
    department: 'Engineering',
    position: 'Junior Developer',
    salary: 65000,
    startDate: '2022-03-01',
    status: 'Active',
    address: 'New York Sub 1',
    tags: ['junior', 'developer'],
  },
  {
    id: '1-2',
    parentId: '1',
    name: 'Child 1-2',
    age: 24,
    email: 'child1-2@company.com',
    phone: '+1-555-0202',
    department: 'Engineering',
    position: 'Frontend Developer',
    salary: 70000,
    startDate: '2021-09-15',
    status: 'Active',
    address: 'New York Sub 2',
    tags: ['frontend', 'react'],
  },
  {
    id: '1-3',
    parentId: '1',
    name: 'Child 1-3',
    age: 26,
    email: 'child1-3@company.com',
    phone: '+1-555-0203',
    department: 'Engineering',
    position: 'Backend Developer',
    salary: 75000,
    startDate: '2021-01-20',
    status: 'Active',
    address: 'New York Sub 3',
    tags: ['backend', 'node'],
  },
  {
    id: '2-1',
    parentId: '2',
    name: 'Child 2-1',
    age: 25,
    email: 'child2-1@company.com',
    phone: '+44-555-0204',
    department: 'Marketing',
    position: 'Mobile Developer',
    salary: 68000,
    startDate: '2021-11-10',
    status: 'Active',
    address: 'London Sub 1',
    tags: ['mobile', 'ios'],
  },
  {
    id: '2-2',
    parentId: '2',
    name: 'Child 2-2',
    age: 27,
    email: 'child2-2@company.com',
    phone: '+44-555-0205',
    department: 'Marketing',
    position: 'Android Developer',
    salary: 72000,
    startDate: '2021-05-03',
    status: 'Inactive',
    address: 'London Sub 2',
    tags: ['android', 'kotlin'],
  },
  {
    id: '3-1',
    parentId: '3',
    name: 'Child 3-1',
    age: 23,
    email: 'child3-1@company.com',
    phone: '+61-555-0206',
    department: 'DevOps',
    position: 'DevOps Engineer',
    salary: 78000,
    startDate: '2022-01-05',
    status: 'Active',
    address: 'Sydney Sub 1',
    tags: ['devops', 'docker'],
  },
  {
    id: '3-2',
    parentId: '3',
    name: 'Child 3-2',
    age: 28,
    email: 'child3-2@company.com',
    phone: '+61-555-0207',
    department: 'DevOps',
    position: 'Cloud Engineer',
    salary: 82000,
    startDate: '2020-08-14',
    status: 'Active',
    address: 'Sydney Sub 2',
    tags: ['cloud', 'aws'],
  },
  {
    id: '4-1',
    parentId: '4',
    name: 'Child 4-1',
    age: 30,
    email: 'child4-1@company.com',
    phone: '+81-555-0208',
    department: 'Security',
    position: 'Security Engineer',
    salary: 88000,
    startDate: '2020-02-28',
    status: 'Active',
    address: 'Tokyo Sub 1',
    tags: ['security', 'cyber'],
  },
  {
    id: '4-2',
    parentId: '4',
    name: 'Child 4-2',
    age: 32,
    email: 'child4-2@company.com',
    phone: '+81-555-0209',
    department: 'AI',
    position: 'AI Engineer',
    salary: 95000,
    startDate: '2019-12-01',
    status: 'Active',
    address: 'Tokyo Sub 2',
    tags: ['ai', 'machine'],
  },
  {
    id: '5-1',
    parentId: '5',
    name: 'Child 5-1',
    age: 21,
    email: 'child5-1@company.com',
    phone: '+33-555-0210',
    department: 'Design',
    position: 'UI/UX Designer',
    salary: 58000,
    startDate: '2022-06-20',
    status: 'Active',
    address: 'Paris Sub 1',
    tags: ['ui', 'ux'],
  },
  {
    id: '5-2',
    parentId: '5',
    name: 'Child 5-2',
    age: 24,
    email: 'child5-2@company.com',
    phone: '+33-555-0211',
    department: 'Design',
    position: 'Graphic Designer',
    salary: 62000,
    startDate: '2021-10-12',
    status: 'Active',
    address: 'Paris Sub 2',
    tags: ['graphic', 'design'],
  },
  {
    id: '6-1',
    parentId: '6',
    name: 'Child 6-1',
    age: 29,
    email: 'child6-1@company.com',
    phone: '+49-555-0212',
    department: 'Database',
    position: 'Database Admin',
    salary: 80000,
    startDate: '2020-04-15',
    status: 'Active',
    address: 'Berlin Sub 1',
    tags: ['database', 'sql'],
  },
  {
    id: '6-2',
    parentId: '6',
    name: 'Child 6-2',
    age: 31,
    email: 'child6-2@company.com',
    phone: '+49-555-0213',
    department: 'Network',
    position: 'Network Admin',
    salary: 76000,
    startDate: '2020-07-01',
    status: 'Pending',
    address: 'Berlin Sub 2',
    tags: ['network', 'admin'],
  },
  {
    id: '7-1',
    parentId: '7',
    name: 'Child 7-1',
    age: 26,
    email: 'child7-1@company.com',
    phone: '+7-555-0214',
    department: 'Analytics',
    position: 'Data Analyst',
    salary: 72000,
    startDate: '2021-03-10',
    status: 'Active',
    address: 'Moscow Sub 1',
    tags: ['python', 'data'],
  },
  {
    id: '7-2',
    parentId: '7',
    name: 'Child 7-2',
    age: 28,
    email: 'child7-2@company.com',
    phone: '+7-555-0215',
    department: 'ML',
    position: 'ML Engineer',
    salary: 85000,
    startDate: '2020-11-25',
    status: 'Active',
    address: 'Moscow Sub 2',
    tags: ['ml', 'tensorflow'],
  },
  {
    id: '8-1',
    parentId: '8',
    name: 'Child 8-1',
    age: 25,
    email: 'child8-1@company.com',
    phone: '+82-555-0216',
    department: 'Product',
    position: 'Product Manager',
    salary: 78000,
    startDate: '2021-08-08',
    status: 'Active',
    address: 'Seoul Sub 1',
    tags: ['product', 'manager'],
  },
  {
    id: '8-2',
    parentId: '8',
    name: 'Child 8-2',
    age: 27,
    email: 'child8-2@company.com',
    phone: '+82-555-0217',
    department: 'Business',
    position: 'Business Analyst',
    salary: 74000,
    startDate: '2021-04-16',
    status: 'Active',
    address: 'Seoul Sub 2',
    tags: ['business', 'analyst'],
  },
  {
    id: '9-1',
    parentId: '9',
    name: 'Child 9-1',
    age: 24,
    email: 'child9-1@company.com',
    phone: '+91-555-0218',
    department: 'QA',
    position: 'Automation Tester',
    salary: 58000,
    startDate: '2022-02-05',
    status: 'Active',
    address: 'Mumbai Sub 1',
    tags: ['automation', 'test'],
  },
  {
    id: '9-2',
    parentId: '9',
    name: 'Child 9-2',
    age: 26,
    email: 'child9-2@company.com',
    phone: '+91-555-0219',
    department: 'QA',
    position: 'Manual Tester',
    salary: 55000,
    startDate: '2021-12-20',
    status: 'Active',
    address: 'Mumbai Sub 2',
    tags: ['manual', 'testing'],
  },
  {
    id: '10-1',
    parentId: '10',
    name: 'Child 10-1',
    age: 28,
    email: 'child10-1@company.com',
    phone: '+1-555-0220',
    department: 'Architecture',
    position: 'Solution Architect',
    salary: 92000,
    startDate: '2020-09-30',
    status: 'Active',
    address: 'Toronto Sub 1',
    tags: ['solution', 'architect'],
  },
  {
    id: '10-2',
    parentId: '10',
    name: 'Child 10-2',
    age: 30,
    email: 'child10-2@company.com',
    phone: '+1-555-0221',
    department: 'Architecture',
    position: 'System Designer',
    salary: 88000,
    startDate: '2020-06-12',
    status: 'Active',
    address: 'Toronto Sub 2',
    tags: ['system', 'design'],
  },

  // Level 2 子节点
  {
    id: '1-1-1',
    parentId: '1-1',
    name: 'Grandchild 1-1-1',
    age: 20,
    email: 'grand1-1-1@company.com',
    phone: '+1-555-0301',
    department: 'Engineering',
    position: 'Intern',
    salary: 45000,
    startDate: '2023-01-10',
    status: 'Active',
    address: 'NY Sub Sub 1',
    tags: ['intern', 'fresh'],
  },
  {
    id: '1-1-2',
    parentId: '1-1',
    name: 'Grandchild 1-1-2',
    age: 21,
    email: 'grand1-1-2@company.com',
    phone: '+1-555-0302',
    department: 'Engineering',
    position: 'Student Developer',
    salary: 48000,
    startDate: '2022-09-01',
    status: 'Active',
    address: 'NY Sub Sub 2',
    tags: ['student', 'learn'],
  },
  {
    id: '1-2-1',
    parentId: '1-2',
    name: 'Grandchild 1-2-1',
    age: 22,
    email: 'grand1-2-1@company.com',
    phone: '+1-555-0303',
    department: 'Engineering',
    position: 'Frontend Trainee',
    salary: 50000,
    startDate: '2022-07-15',
    status: 'Active',
    address: 'NY Sub Sub 3',
    tags: ['css', 'html'],
  },
  {
    id: '2-1-1',
    parentId: '2-1',
    name: 'Grandchild 2-1-1',
    age: 23,
    email: 'grand2-1-1@company.com',
    phone: '+44-555-0304',
    department: 'Mobile',
    position: 'iOS Trainee',
    salary: 52000,
    startDate: '2022-05-20',
    status: 'Active',
    address: 'London Sub Sub 1',
    tags: ['swift', 'xcode'],
  },
  {
    id: '2-2-1',
    parentId: '2-2',
    name: 'Grandchild 2-2-1',
    age: 24,
    email: 'grand2-2-1@company.com',
    phone: '+44-555-0305',
    department: 'Mobile',
    position: 'Android Trainee',
    salary: 54000,
    startDate: '2022-03-08',
    status: 'Inactive',
    address: 'London Sub Sub 2',
    tags: ['java', 'gradle'],
  },
  {
    id: '3-1-1',
    parentId: '3-1',
    name: 'Grandchild 3-1-1',
    age: 21,
    email: 'grand3-1-1@company.com',
    phone: '+61-555-0306',
    department: 'DevOps',
    position: 'DevOps Trainee',
    salary: 56000,
    startDate: '2022-11-30',
    status: 'Active',
    address: 'Sydney Sub Sub 1',
    tags: ['k8s', 'helm'],
  },
  {
    id: '4-1-1',
    parentId: '4-1',
    name: 'Grandchild 4-1-1',
    age: 25,
    email: 'grand4-1-1@company.com',
    phone: '+81-555-0307',
    department: 'Security',
    position: 'Security Analyst',
    salary: 62000,
    startDate: '2021-06-18',
    status: 'Active',
    address: 'Tokyo Sub Sub 1',
    tags: ['pen', 'test'],
  },
  {
    id: '5-1-1',
    parentId: '5-1',
    name: 'Grandchild 5-1-1',
    age: 19,
    email: 'grand5-1-1@company.com',
    phone: '+33-555-0308',
    department: 'Design',
    position: 'Design Intern',
    salary: 42000,
    startDate: '2023-03-15',
    status: 'Active',
    address: 'Paris Sub Sub 1',
    tags: ['sketch', 'figma'],
  },
  {
    id: '6-1-1',
    parentId: '6-1',
    name: 'Grandchild 6-1-1',
    age: 27,
    email: 'grand6-1-1@company.com',
    phone: '+49-555-0309',
    department: 'Database',
    position: 'DBA Junior',
    salary: 65000,
    startDate: '2021-09-22',
    status: 'Active',
    address: 'Berlin Sub Sub 1',
    tags: ['mongo', 'redis'],
  },
  {
    id: '7-1-1',
    parentId: '7-1',
    name: 'Grandchild 7-1-1',
    age: 24,
    email: 'grand7-1-1@company.com',
    phone: '+7-555-0310',
    department: 'Analytics',
    position: 'Data Analyst Jr',
    salary: 58000,
    startDate: '2022-04-12',
    status: 'Active',
    address: 'Moscow Sub Sub 1',
    tags: ['pandas', 'numpy'],
  },
  {
    id: '8-1-1',
    parentId: '8-1',
    name: 'Grandchild 8-1-1',
    age: 23,
    email: 'grand8-1-1@company.com',
    phone: '+82-555-0311',
    department: 'Product',
    position: 'Product Analyst',
    salary: 60000,
    startDate: '2022-08-05',
    status: 'Pending',
    address: 'Seoul Sub Sub 1',
    tags: ['agile', 'scrum'],
  },
  {
    id: '9-1-1',
    parentId: '9-1',
    name: 'Grandchild 9-1-1',
    age: 22,
    email: 'grand9-1-1@company.com',
    phone: '+91-555-0312',
    department: 'QA',
    position: 'Test Automation Jr',
    salary: 48000,
    startDate: '2022-12-01',
    status: 'Active',
    address: 'Mumbai Sub Sub 1',
    tags: ['selenium', 'cypress'],
  },
  {
    id: '10-1-1',
    parentId: '10-1',
    name: 'Grandchild 10-1-1',
    age: 26,
    email: 'grand10-1-1@company.com',
    phone: '+1-555-0313',
    department: 'Architecture',
    position: 'API Developer',
    salary: 68000,
    startDate: '2021-11-18',
    status: 'Active',
    address: 'Toronto Sub Sub 1',
    tags: ['microservice', 'api'],
  },

  // Level 3 子节点
  {
    id: '1-1-1-1',
    parentId: '1-1-1',
    name: 'Great-grandchild 1-1-1-1',
    age: 18,
    email: 'great1-1-1-1@company.com',
    phone: '+1-555-0401',
    department: 'Engineering',
    position: 'Trainee',
    salary: 35000,
    startDate: '2023-06-01',
    status: 'Active',
    address: 'NY Deep 1',
    tags: ['trainee', 'new'],
  },
  {
    id: '1-1-1-2',
    parentId: '1-1-1',
    name: 'Great-grandchild 1-1-1-2',
    age: 19,
    email: 'great1-1-1-2@company.com',
    phone: '+1-555-0402',
    department: 'Engineering',
    position: 'Bootcamp Graduate',
    salary: 38000,
    startDate: '2023-04-15',
    status: 'Active',
    address: 'NY Deep 2',
    tags: ['bootcamp', 'coding'],
  },
  {
    id: '2-1-1-1',
    parentId: '2-1-1',
    name: 'Great-grandchild 2-1-1-1',
    age: 20,
    email: 'great2-1-1-1@company.com',
    phone: '+44-555-0403',
    department: 'Mobile',
    position: 'App Store Trainee',
    salary: 40000,
    startDate: '2023-02-20',
    status: 'Active',
    address: 'London Deep 1',
    tags: ['apple', 'store'],
  },
  {
    id: '3-1-1-1',
    parentId: '3-1-1',
    name: 'Great-grandchild 3-1-1-1',
    age: 19,
    email: 'great3-1-1-1@company.com',
    phone: '+61-555-0404',
    department: 'DevOps',
    position: 'Container Specialist',
    salary: 42000,
    startDate: '2023-01-05',
    status: 'Active',
    address: 'Sydney Deep 1',
    tags: ['container', 'deploy'],
  },
  {
    id: '5-1-1-1',
    parentId: '5-1-1',
    name: 'Great-grandchild 5-1-1-1',
    age: 17,
    email: 'great5-1-1-1@company.com',
    phone: '+33-555-0405',
    department: 'Design',
    position: 'Prototype Designer',
    salary: 32000,
    startDate: '2023-07-10',
    status: 'Active',
    address: 'Paris Deep 1',
    tags: ['prototype', 'wire'],
  },
  {
    id: '7-1-1-1',
    parentId: '7-1-1',
    name: 'Great-grandchild 7-1-1-1',
    age: 22,
    email: 'great7-1-1-1@company.com',
    phone: '+7-555-0406',
    department: 'Analytics',
    position: 'Statistics Analyst',
    salary: 44000,
    startDate: '2022-10-30',
    status: 'Active',
    address: 'Moscow Deep 1',
    tags: ['statistics', 'math'],
  },
  {
    id: '9-1-1-1',
    parentId: '9-1-1',
    name: 'Great-grandchild 9-1-1-1',
    age: 20,
    email: 'great9-1-1-1@company.com',
    phone: '+91-555-0407',
    department: 'QA',
    position: 'Bug Tracker',
    salary: 36000,
    startDate: '2023-05-08',
    status: 'Active',
    address: 'Mumbai Deep 1',
    tags: ['bug', 'report'],
  },
]

const rowSelection = {
  width: 20,
}

export function TreeTableSizeDemo() {
  const [stateColumns, setColumnCount] = useState(columns) // 初始显示所有5列

  const handleReduceColumns = () => {
    setColumnCount(
      columns.map((column) => {
        return {
          ...column,
          width: 200,
        }
      }),
    ) // 最少保留1列
  }
  const handleReduceColumnsHalf = () => {
    setColumnCount(
      columns.map((column) => {
        return {
          ...column,
          width: 50,
        }
      }),
    ) // 最少保留1列
  }

  const handleResetColumns = () => {
    setColumnCount(columns) // 重置为显示所有列
  }

  return (
    <div
      style={{
        width: 800,
        height: 300,
      }}
    >
      <Space style={{ marginBottom: 16 }}>
        <Button onClick={handleReduceColumns}>每列200</Button>
        <Button onClick={handleReduceColumnsHalf}>每列50</Button>
        <Button onClick={handleResetColumns}>重置所有列</Button>
      </Space>

      <Table
        rowSelection={rowSelection}
        columns={stateColumns}
        dataSource={data}
        parentProp="parentId"
        idProp="id"
      />
    </div>
  )
}

export default TreeTableSizeDemo
